# ────────────────────────────────────────
# Cloudflare Workers configuration for Pages
# ────────────────────────────────────────

name = "promowho2industries"
compatibility_date = "2025-12-30"

[[routes]]
pattern = "who2industries.systems"
custom_domain = true

[assets]
directory = "./assets"
#not_found_handling = "single-page-application"
#binding = "ASSETS"
#run_worker_first = [ "/api/*", "!/api/docs/*" ]
