# ────────────────────────────────────────
# Cloudflare Workers configuration for Pages
# ────────────────────────────────────────

name = "who2industries-coming-soon"
compatibility_date = "2025-12-30"

pattern = "who2industries.systems"
custom_domain = true

assets = { directory = "./assets", binding = "ASSETS", html_handling = "force-trailing-slash", not_found_handling = "404-page" }
